# Generated by Django 3.2.25 on 2025-07-28 19:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerDiemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='', max_length=120, verbose_name='Cargo')),
                ('cds', models.CharField(blank=True, max_length=10, null=True, verbose_name='CDS')),
                ('valor_nacional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Nacional')),
                ('valor_internacional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Internacional')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now, verbose_name='Vigente Desde')),
                ('vigente_ate', models.DateField(blank=True, null=True, verbose_name='Vigente Até')),
            ],
            options={
                'verbose_name': 'Valor de Diária',
                'verbose_name_plural': 'Valores de Diárias',
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_orcamentaria', models.CharField(default='', max_length=120, verbose_name='Unidade Orçamentária')),
                ('orgao_solicitante', models.CharField(default='', max_length=120, verbose_name='Órgão Solicitante')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('itinerario', models.CharField(max_length=255, verbose_name='Itinerário')),
                ('data_ida', models.DateField(verbose_name='Data de Ida')),
                ('data_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('transporte_tipo', models.CharField(choices=[('oficial', 'Oficial'), ('proprio', 'Próprio'), ('comercial', 'Comercial')], default='oficial', max_length=20, verbose_name='Tipo de Transporte')),
                ('transporte_meio', models.CharField(choices=[('aereo', 'Aéreo'), ('terrestre', 'Terrestre'), ('fluvial', 'Fluvial')], default='terrestre', max_length=20, verbose_name='Meio de Transporte')),
                ('descricao_veiculo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Veículo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Solicitação de Viagem',
                'verbose_name_plural': 'Solicitações de Viagem',
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('cds', models.CharField(blank=True, max_length=10, null=True, verbose_name='CDS')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('banco', models.CharField(max_length=60, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta_corrente', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unitário')),
                ('qtd_diarias', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Quantidade de Diárias')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total')),
                ('tipo', models.CharField(choices=[('motorista', 'Motorista'), ('passageiro', 'Passageiro')], default='passageiro', max_length=15, verbose_name='Tipo')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='travel.travelrequest')),
            ],
            options={
                'verbose_name': 'Viajante',
                'verbose_name_plural': 'Viajantes',
            },
        ),
    ]
