# Generated by Django 3.2.25 on 2025-07-28 20:06

from django.db import migrations
import travel.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='agencia',
            field=travel.utils.fields.EncryptedCharField(max_length=255, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='banco',
            field=travel.utils.fields.EncryptedCharField(max_length=255, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='conta_corrente',
            field=travel.utils.fields.EncryptedCharField(max_length=255, verbose_name='Conta Corrente'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='cpf',
            field=travel.utils.fields.EncryptedCharField(max_length=255, verbose_name='CPF'),
        ),
    ]
