# Generated by Django 5.2.5 on 2025-08-12 12:33

import apps.travel.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_auto_20250728_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="agencia",
            field=apps.travel.utils.fields.EncryptedCharField(
                max_length=255, verbose_name="Agência"
            ),
        ),
        migrations.AlterField(
            model_name="traveler",
            name="banco",
            field=apps.travel.utils.fields.EncryptedCharField(
                max_length=255, verbose_name="Banco"
            ),
        ),
        migrations.AlterField(
            model_name="traveler",
            name="conta_corrente",
            field=apps.travel.utils.fields.EncryptedCharField(
                max_length=255, verbose_name="Conta Corrente"
            ),
        ),
        migrations.AlterField(
            model_name="traveler",
            name="cpf",
            field=apps.travel.utils.fields.EncryptedCharField(
                max_length=255, verbose_name="CPF"
            ),
        ),
    ]
