name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      working-directory: ./backend
      run: poetry install --no-root

    - name: Run Ruff (Linting)
      working-directory: ./backend
      run: poetry run ruff check apps/ config/

    - name: Run MyPy (Type Checking)
      working-directory: ./backend
      run: poetry run mypy apps/ config/

    - name: Run Safety (Security Check)
      working-directory: ./backend
      run: poetry run safety check

    - name: Run Tests
      working-directory: ./backend
      run: poetry run pytest
